import os

dirs = [
    "docs",
    "client/public",
    "client/src/screens/ActionQueue",
    "client/src/screens/InvestigationWorkspace",
    "client/src/screens/HotspotMap",
    "client/src/screens/NetworkGraph",
    "client/src/screens/RiskDetail",
    "client/src/screens/AuditLog",
    "client/src/screens/ReportExport",
    "client/src/screens/AdminConsole",
    "client/src/screens/LiveFeed",
    "client/src/screens/StateOverview",
    "client/src/components",
    "client/src/api",
    "client/src/state",
    "client/src/styles",
    "client/build",
    "functions/data-fusion/adapters",
    "functions/data-fusion/schema",
    "functions/ocr-ingestion",
    "functions/risk-engine",
    "functions/hotspot-engine",
    "functions/network-analysis",
    "functions/audit-log",
    "functions/outcome-loop",
    "functions/report-export",
    "functions/event-triggers",
    "functions/auth-hooks",
    "functions/notifications",
    "data/districts/bangalore-urban/stations/whitefield",
    "data/districts/bangalore-urban/stations/hal",
    "data/districts/bangalore-urban/stations/bellandur",
    "data/districts/bangalore-urban/stations/indiranagar",
    "data/districts/mysuru",
    "data/districts/mangaluru",
    "data/districts/belagavi",
    "data/districts/kalaburagi",
    "data/generators",
    "data/seed",
    "simulation/event-generator",
    "simulation/crime-generator",
    "simulation/incident-stream",
    "simulation/patrol-generator",
    "simulation/scheduler",
    "simulation/realtime-feed",
    "shared/types",
    "shared/schemas",
    "shared/constants",
    "shared/utils",
    "models/hotspot",
    "models/network",
    "models/prediction",
    "models/recommendation",
    "models/explainability",
    "analytics/hotspot",
    "analytics/network",
    "analytics/correlation",
    "analytics/trend",
    "analytics/prediction",
    "assets/maps/geojson",
    "scripts",
    "tests/unit",
    "tests/integration",
    "tests/simulation",
    "tests/performance",
    "deployment/docker",
    "deployment/terraform",
    "deployment/monitoring",
    "deployment/logging",
    "demo/scripts",
    "demo/datasets",
    "demo/screenshots",
    "demo/videos"
]

files = [
    "catalyst.json",
    ".catalystrc",
    ".gitignore",
    "README.md",
    "docs/PRAHARI_PRD.docx",
    "docs/PRAHARI_Full_Report.docx",
    "docs/api-contracts.md",
    "docs/data-model.md",
    "docs/FUTURE_FEATURES.md",
    "docs/architecture.md",
    "docs/system-design.md",
    "docs/deployment.md",
    "docs/simulation-guide.md",
    "docs/dataset-specification.md",
    "docs/fusion-workflow.md",
    "docs/future-roadmap.md",
    "client/client-package.json",
    "client/public/index.html",
    "client/src/index.jsx",
    "client/src/App.jsx",
    "client/src/api/fusionApi.js",
    "client/src/api/decisionEngineApi.js",
    "client/src/api/auditApi.js",
    "client/src/api/outcomeApi.js",
    "client/src/api/simulationApi.js",
    "functions/data-fusion/catalyst-config.json",
    "functions/data-fusion/index.js",
    "functions/data-fusion/package.json",
    "functions/data-fusion/adapters/whitefield-adapter.js",
    "functions/data-fusion/adapters/hal-adapter.js",
    "functions/data-fusion/adapters/bellandur-adapter.js",
    "functions/data-fusion/adapters/indiranagar-adapter.js",
    "functions/data-fusion/schema/unified-record-schema.js",
    "data/districts/bangalore-urban/district.json",
    "data/districts/bangalore-urban/stations/whitefield/fir.csv",
    "data/districts/bangalore-urban/stations/whitefield/criminals.csv",
    "data/districts/bangalore-urban/stations/whitefield/officers.csv",
    "data/districts/bangalore-urban/stations/whitefield/vehicles.csv",
    "data/districts/bangalore-urban/stations/whitefield/evidence.csv",
    "data/districts/bangalore-urban/stations/whitefield/cases.csv",
    "data/districts/bangalore-urban/stations/hal/fir.csv",
    "data/districts/bangalore-urban/stations/hal/criminals.csv",
    "data/districts/bangalore-urban/stations/hal/officers.csv",
    "data/districts/bangalore-urban/stations/hal/vehicles.csv",
    "data/districts/bangalore-urban/stations/hal/evidence.csv",
    "data/districts/bangalore-urban/stations/hal/cases.csv",
    "data/districts/bangalore-urban/stations/bellandur/fir.csv",
    "data/districts/bangalore-urban/stations/bellandur/criminals.csv",
    "data/districts/bangalore-urban/stations/bellandur/officers.csv",
    "data/districts/bangalore-urban/stations/bellandur/vehicles.csv",
    "data/districts/bangalore-urban/stations/bellandur/evidence.csv",
    "data/districts/bangalore-urban/stations/bellandur/cases.csv",
    "data/districts/bangalore-urban/stations/indiranagar/fir.csv",
    "data/districts/bangalore-urban/stations/indiranagar/criminals.csv",
    "data/districts/bangalore-urban/stations/indiranagar/officers.csv",
    "data/districts/bangalore-urban/stations/indiranagar/vehicles.csv",
    "data/districts/bangalore-urban/stations/indiranagar/evidence.csv",
    "data/districts/bangalore-urban/stations/indiranagar/cases.csv",
    "data/districts/mysuru/district.json",
    "data/districts/mangaluru/district.json",
    "data/districts/belagavi/district.json",
    "data/districts/kalaburagi/district.json",
    "data/generators/generate-station-a.py",
    "data/generators/generate-station-b.py",
    "data/generators/generate-station-c-scanned.py",
    "data/README.md",
    "shared/utils/Crime.js",
    "shared/utils/Case.js",
    "shared/utils/District.js",
    "shared/utils/Station.js",
    "shared/utils/Officer.js",
    "shared/utils/Criminal.js",
    "shared/utils/Recommendation.js",
    "shared/utils/Alert.js",
    "shared/utils/Risk.js",
    "assets/maps/geojson/districts.geojson",
    "assets/maps/geojson/police_stations.geojson",
    "assets/maps/geojson/ward_boundaries.geojson",
    "scripts/deploy.sh",
    "scripts/seed-db.sh",
    "scripts/run-local.sh",
    "demo/demo-script.md",
    "demo/demo-dataset.json",
    "demo/judge-questions.md"
]

base_dir = r"c:\Users\arjun\Desktop\PRAHARI"

for d in dirs:
    os.makedirs(os.path.join(base_dir, d), exist_ok=True)

for f in files:
    full_path = os.path.join(base_dir, f)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    if not os.path.exists(full_path):
        with open(full_path, "w", encoding="utf-8") as fp:
            pass

print("Tree creation complete.")
